//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final01._03._2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public int ID { get; set; }
        public string email { get; set; }
        public string parol { get; set; }
        public string parol1 { get; set; }
    }
}
